# permissions for end users to view mongodbbindings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: mongodbbinding-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: catalog
    app.kubernetes.io/part-of: catalog
    app.kubernetes.io/managed-by: kustomize
  name: mongodbbinding-viewer-role
rules:
- apiGroups:
  - catalog.kubeware.dev
  resources:
  - mongodbbindings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - catalog.kubeware.dev
  resources:
  - mongodbbindings/status
  verbs:
  - get
