# permissions for end users to edit perconaxtradbbindings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: perconaxtradbbinding-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: catalog
    app.kubernetes.io/part-of: catalog
    app.kubernetes.io/managed-by: kustomize
  name: perconaxtradbbinding-editor-role
rules:
- apiGroups:
  - catalog.kubeware.dev
  resources:
  - perconaxtradbbindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - catalog.kubeware.dev
  resources:
  - perconaxtradbbindings/status
  verbs:
  - get
