# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/catalog.kubeware.dev_elasticsearchbindings.yaml
- bases/catalog.kubeware.dev_kafkabindings.yaml
- bases/catalog.kubeware.dev_mariadbbindings.yaml
- bases/catalog.kubeware.dev_memcachedbindings.yaml
- bases/catalog.kubeware.dev_mongodbbindings.yaml
- bases/catalog.kubeware.dev_mysqlbindings.yaml
- bases/catalog.kubeware.dev_perconaxtradbbindings.yaml
- bases/catalog.kubeware.dev_pgbouncerbindings.yaml
- bases/catalog.kubeware.dev_postgresbindings.yaml
- bases/catalog.kubeware.dev_proxysqlbindings.yaml
- bases/catalog.kubeware.dev_redisbindings.yaml
#+kubebuilder:scaffold:crdkustomizeresource

patches:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#- path: patches/webhook_in_elasticsearchbindings.yaml
#- path: patches/webhook_in_kafkabindings.yaml
#- path: patches/webhook_in_mariadbbindings.yaml
#- path: patches/webhook_in_memcachedbindings.yaml
#- path: patches/webhook_in_mongodbbindings.yaml
#- path: patches/webhook_in_mysqlbindings.yaml
#- path: patches/webhook_in_perconaxtradbbindings.yaml
#- path: patches/webhook_in_pgbouncerbindings.yaml
#- path: patches/webhook_in_postgresbindings.yaml
#- path: patches/webhook_in_proxysqlbindings.yaml
#- path: patches/webhook_in_redisbindings.yaml
#+kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable cert-manager, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- path: patches/cainjection_in_elasticsearchbindings.yaml
#- path: patches/cainjection_in_kafkabindings.yaml
#- path: patches/cainjection_in_mariadbbindings.yaml
#- path: patches/cainjection_in_memcachedbindings.yaml
#- path: patches/cainjection_in_mongodbbindings.yaml
#- path: patches/cainjection_in_mysqlbindings.yaml
#- path: patches/cainjection_in_perconaxtradbbindings.yaml
#- path: patches/cainjection_in_pgbouncerbindings.yaml
#- path: patches/cainjection_in_postgresbindings.yaml
#- path: patches/cainjection_in_proxysqlbindings.yaml
#- path: patches/cainjection_in_redisbindings.yaml
#+kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
