name: CI

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}-ci
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.21'

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Prepare Host
        run: |
          sudo apt-get -qq update || true
          sudo apt-get install -y --no-install-recommends apt-transport-https ca-certificates curl bzip2
          curl -fsSL -o restic.bz2 https://github.com/restic/restic/releases/download/v0.15.1/restic_0.15.1_linux_amd64.bz2
          bzip2 -d restic.bz2
          chmod 755 restic
          sudo mv restic /usr/bin/restic

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
